<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\AutoTripleTriadGrind\Core\Triad\Logic\**\*.cs" Link="Logic\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\AutoTripleTriadGrind\Core\Triad\Data\TriadCard.cs" Link="Data\TriadCard.cs" />
    <Compile Include="..\AutoTripleTriadGrind\Core\Triad\Data\TriadCardType.cs" Link="Data\TriadCardType.cs" />
    <Compile Include="..\AutoTripleTriadGrind\Core\Triad\Data\TriadRuleId.cs" Link="Data\TriadRuleId.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Collections" />
    <Using Include="System.Collections.Generic" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
